apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: nginx
  labels:
    name: nginx
spec:
  type: LoadBalancer
  ports:
   - protocol: TCP
     port: 80
  selector:
    run: nginx
